spring.application.name=CNE_Project
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect
spring.jpa.hibernate.ddl-auto=update 

# JWT Paths
jwt.keys.private.path=classpath:certs/private.pem
jwt.keys.public.path=classpath:certs/public.pem